### ISSUE TITLE
Issue in training SCARF gen with GNPS data

### ISSUE THREAD

**Issue by yuanqidu** [samgoldman97/ms-pred#8]
I am getting the following error when training the SCARF gen model for GNPS data. It seems when preparing the dataset, there is some issue with the DGL object. I trained to dive into it but didn't find any related things with self.chandle, I am wondering if you have encountered this issue before as well?

UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:172.)
  return th.as_tensor(data, dtype=dtype)
/mnt/beegfs/bulk/mirror/yuanqi/anaconda3/envs/mspred/lib/python3.10/site-packages/dgl/backend/pytorch/tensor.py:52: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:172.)
  return th.as_tensor(data, dtype=dtype)
/mnt/beegfs/bulk/mirror/yuanqi/anaconda3/envs/mspred/lib/python3.10/site-packages/dgl/backend/pytorch/tensor.py:52: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:172.)
  return th.as_tensor(data, dtype=dtype)
/mnt/beegfs/bulk/mirror/yuanqi/anaconda3/envs/mspred/lib/python3.10/site-packages/dgl/backend/pytorch/tensor.py:52: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:172.)
  return th.as_tensor(data, dtype=dtype)
  0%|                                                                                                                              | 0/102 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/beegfs/bulk/mirror/yuanqi/ms-pred/src/ms_pred/scarf_pred/train_gen.py", line 299, in <module>
    train_model()
  File "/mnt/beegfs/bulk/mirror/yuanqi/ms-pred/src/ms_pred/scarf_pred/train_gen.py", line 144, in train_model
    train_dataset = scarf_data.ScarfDataset(
  File "/mnt/beegfs/bulk/mirror/yuanqi/ms-pred/src/ms_pred/scarf_pred/scarf_data.py", line 380, in __init__
    self.mol_graphs = common.chunked_parallel(
  File "/mnt/beegfs/bulk/mirror/yuanqi/ms-pred/src/ms_pred/common/parallel_utils.py", line 98, in chunked_parallel
    list_outputs = simple_parallel(

....

edata_schemes={'e': Scheme(shape=(5,), dtype=torch.float32)}), Graph(num_nodes=59, num_edges=124,                                     
      ndata_schemes={'h': Scheme(shape=(106,), dtype=torch.float32)}
      edata_schemes={'e': Scheme(shape=(5,), dtype=torch.float32)}), Graph(num_nodes=55, num_edges=114,                                     
      ndata_schemes={'h': Scheme(shape=(106,), dtype=torch.float32)}
      edata_schemes={'e': Scheme(shape=(5,), dtype=torch.float32)})]'. Reason: 'TypeError('self.chandle cannot be converted to a Python object for pickling')'

**Comment by samgoldman97** [comment]
It looks like a parallelism issue. Can you try training with 0 workers first to see if that helps? Otherwise I would need a little more time to dive into this later.

**Comment by yuanqidu** [comment]
It works with 0 workers, do you have any insight why this parallelization error happened?

**Comment by samgoldman97** [comment]
Not off the top of my head. If you send the call signature, I can try to see if it breaks with my environment as well.

**Comment by yuanqidu** [comment]
Absolutely, it may also be my enviroment, I also run the other model training, seems setting workers to 0 is important on my machine. Thanks again for your prompt response and excellent work!

`sh run_scripts/scarf_model/02_run_scarf_gen_train.sh`

**Comment by samgoldman97** [comment]
I was also getting errors on parallelism (maybe due to the latest massformer code changing some versions). I switched a function in parallel_utils, and at least for me, this seemed to make the errors with multiple workers disappear. If you can't get it working and still want to train with multiple workers, I would just modify the parallel_utils file to remove that logic. 

Let me know if this fixes things for you as well.

**Comment by yuanqidu** [comment]
Yeah, setting works to 0 worked fine and it doesn't seem to be very slow.
